<?php

/**
 *  * Implements hook_entity_bundle_field_info_alter().
 */
function merci_open_hours_constraint_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node'  && !empty($fields['merci_reservation_items'])) {
    $fields['merci_reservation_items']->addConstraint('MerciOpenHours', array('date_field' => 'merci_reservation_date', 'office_hours_field' => 'field_office_hours', 'reservable_hours_field' => 'field_reservable_hours'));
  }
}
