<?php

/**
 * @file
 * merci_ui functions
 */

function merci_ui_php_eval($code, $account = NULL) {
  ob_start();
  print eval('?>'. $code);
  $output = ob_get_clean();
  return $output;
}

/**
 * Implements hook_views_api().
 */
function merci_ui_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'merci_ui') . '/includes',
  );
}

/**
 * om_navigation_om_navigation_items function.
 * Sample implementation of hook_om_navigation_items
 * @access public
 *
 * @param mixed $context
 *
 * @return void
 */
function merci_ui_om_navigation_items($context) {
  $items = array();

  $items['normal'][0] = array(
    'zone' => 'private',
    'status' => 'merci_ui_user_tab_access',
    'value' => 'merci_ui_user_tab',
    'label' => 'My Reservation',
    'path' => 'reservations',
    'weight' => 10,
  );

  return $items;
}


