<?php

function merci_permissions_merci_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors){
  if (empty($items)) {
    return;
  }
  // Does the user have access to manage reservations or this content type?
  $merci_permission_field = $field['settings']['handler_settings']['behaviors']['merci']['merci_permissions']['merci_permission_field'];

  $user = user_load_by_name($entity->name);

  $permissions = $user->{$merci_permission_field}[$langcode];

  foreach ($items as $delta => $item) {
    $allowed = false;
    foreach ($permissions as $index => $permission) {
      if ($permission['target_id'] == $item['target_id']) {
        $allowed = true;
        break;
      }
    }
    if (!$allowed) {
      $errors[$field['field_name']][$langcode][$delta][] = array(
        'error' => 'merci_item_permission',
        'message' => t('%name: you don not have permission.', array('%name' => $instance['label'])),
      );
    }
  }
}

function merci_permissions_merci_settings_form($field, $instance, &$form) {
  /**
   * get all date fields on the site organized by entity and bundle
   */

  $fields_info = field_info_instances('user');
  $reference_fields = array('disabled' => t('Disabled'));
  foreach ($fields_info as $bundle => $fields) {
    foreach ($fields as $field_name => $info) {
      $more_info = field_info_field($field_name);
      if ( $more_info['type'] == 'entityreference') {
        $reference_fields[$field_name] = $info['label'];
      }
    }
  }

  $settings = $field['settings']['handler_settings']['behaviors']['merci']['merci_permissions'];
  $default_value = array_key_exists('merci_permission_field', $settings) ? $settings['merci_permission_field'] : 'disabled';
  $form['merci_permissions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Merci permissions'),
    '#collapsible' => TRUE,
    '#collapsed' => $default_value == 'disabled' ? true : false, 
  );

  if (empty($reference_fields)) {
    $form['merci_permissions']['merci_permission_field'] = array(
      '#markup' => t('Please add a entityreference field to the user entity to use to filter reservations by permission.')
    );
  } else {
    $form['merci_permissions']['merci_permission_field'] = array(
      '#type' => 'select',
      '#title' => t('Permission field'),
      '#options' => $reference_fields,
      '#default_value' => $default_value,
      '#description' => t('Select the entityreference field to use to limit reservations of this entity field.'),
    );
  }
}
