<?php
// $Id$ 

/**
 * @file
 * merci_staff functions
 */

function merci_staff_menu() {
  $items = array();

  if (module_exists('civicrm')) {
    $items['user/autocompletecivi'] = array(
      'title' => 'User autocomplete',
      'page callback' => 'merci_staff_autocomplete',
      'access callback' => 'user_access',
      'access arguments' => array('access user profiles'),
      'type' => MENU_CALLBACK,
    );
  }

  // Callback for AJAX adding of item selectors.
  $items['mercistaff/updatename'] = array(
    'page callback' => 'merci_staff_update_name',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // Callback for AJAX adding of item selectors.
  $items['mercistaff/js'] = array(
    'title' => 'Javascript Choice Form',
    'page callback' => 'merci_staff_choice_js',
    'access arguments' => array('access content'),
    'file' => 'includes/menu.inc',
    'file path' => drupal_get_path('module', 'merci'), 
    'type' => MENU_CALLBACK,
  );

  $items['mercistaff/datefilter'] = array(
    'title' => 'Javascript Choice Form',
    'page callback' => 'merci_staff_date_filter_js',
    'access arguments' => array('access content'),
    'file' => 'includes/menu.inc',
    'file path' => drupal_get_path('module', 'merci'), 
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function merci_staff_user_load($post = NULL) {
  static $admin_user;
  global $user;
  if(empty($admin_user)) {
    $admin_user = $user;
  }
  if($post and !$post['override'] and ($newuser = user_load(array('name' => $post['name'])))){
    $user = $newuser;
  } else {
    $user = $admin_user;
  }
}

function merci_staff_choice_js() {
  merci_staff_user_load($_POST);
  merci_choice_js(); 
  merci_staff_user_load();
}

function merci_staff_date_filter_js() {
  merci_staff_user_load($_POST);
  merci_date_filter_js(); 
  merci_staff_user_load();
}


/**
* Implementation of hook_form_alter
**/

function merci_staff_form_alter(&$form, &$form_state,$form_id) {

  if($form_id != 'merci_reservation_node_form') {
    return;
  }
  if (isset($form_state['node'])) {
      $node = $form_state['node'] + (array)$form['#node'];
  } else {
    $node = $form['#node'];
  }
  $node = (object) $node;
  //merci_staff_user_load();
  if (user_access('administer MERCI') || user_access('manage MERCI')) {
    // Move the author field and set autocomplete and ahah handlers.
    $form['name'] = $form['author']['name'];
    $form['name']['#title'] = 'Reserve for';
    $form['name']['#weight'] = -99;
    $form['name']['#default_value'] = $node->name ? $node->name : '';
    if (module_exists('civicrm')) {
      $form['name']['#autocomplete_path'] = 'user/autocompletecivi';
    }
    $form['name']['#ahah'] = array(
      'path' => 'mercistaff/updatename',
      //'wrapper' => 'edit-og-groups-wrapper',
      'wrapper' => 'merci-staff-edit-form-wrapper',
      'method' => 'replace',
      'effect' => 'fade',

      );

    unset($form['author']['name']);

    // We need our own ahah handler to filter by the submitted name.
    // The submit handler can remain the same as this function is called from that to rebuild the choices filtered by the submitted name.
    $form['field_merci_date'][0]['merci_date_filter'] = array(
      '#type' => 'submit',
      '#value' => t('Limit Lists to Available Items'),
      '#weight' => 10,
      '#submit' => array('merci_date_filter'),
      '#ahah' => array(
        'path' => 'mercistaff/datefilter',
        'wrapper' => 'merci-choices',
        'method' => 'replace',
        'effect' => 'fade',
      ),

    );

    // We name our button 'merci_more' to avoid conflicts with other modules using
    // AHAH-enabled buttons with the id 'more'.
    // We need our own ahah handler to filter by the submitted name.
    // The submit handler can remain the same as this function is called from that to rebuild the choices filtered by the submitted name.
    $form['choice_wrapper']['merci_more'] = array(
      '#type' => 'submit',
      '#value' => t('Add more items'),
      '#description' => t("If the number of items above isn't enough, click here to add more items."),
      '#weight' => 1,
      // If no javascript action.
      '#submit' => array('merci_more_choices_submit'),
      '#ahah' => array(
        'path' => 'mercistaff/js',
        'wrapper' => 'merci-choices',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );

    //create override checkbox          
    $form['override'] = array(
      //'#type' => 'optionwidgets_onoff',
      '#type' => 'checkbox',
      '#title' => 'Override Validation',
      '#default_value' => $node->override,
      '#weight' => -97,
      '#columns' => 0
    );
    $form['#prefix'] = '<div id="merci-staff-edit-form-wrapper">';
    $form['#suffix'] = '</div>';

    // Override the validation function so we can validate as the submitted user.
    $key = array_search('merci_node_validate',$form['#validate']);
    $form['#validate'][$key] = 'merci_staff_node_validate';

    // Recreate the groups and choices based on the submitted name.
    merci_staff_user_load((array)$node);

    if (module_exists('og')) {
      if(!isset($form['og_nodeapi'])) {
        db_query("UPDATE {system} SET weight = 10 WHERE name = 'merci_staff'");
      }
      unset($form['og_nodeapi']);
      og_form_add_og_audience($form,$form_state);
    }

    // Add the current choices to the form.
    $reset = true;
    foreach($form['choice_wrapper']['choice'] as $delta => $choice){
      $default = isset($node->choice[$delta]['item']) ? $node->choice[$delta]['item'] : '';
      if(is_numeric($delta)){
        $form['choice_wrapper']['choice'][$delta] = _merci_choice_form($node, $form_state, $delta, $default, $reset);
        unset($reset);
      }
    }
    merci_staff_user_load();
  }
}

function merci_staff_node_validate($form, &$form_state) {
  merci_staff_user_load($form_state['values']);
  merci_node_validate($form, &$form_state);
  merci_staff_user_load();
}
/**
 ** Menu callback; Retrieve a JSON object containing autocomplete suggestions for existing users.
 **/
function merci_staff_autocomplete($string = '') {
  $matches = array();
  if ($string) {

    if ( ! civicrm_initialize( ) ) {
      return;
    }
    $fields = content_fields();
    $field = $fields[$field_name];
    $matches = array();

    $references = _merci_staff_potential_references($field, $string);
    foreach ($references as $id => $row) {
      // Add a class wrapper for a few required CSS overrides.
      $matches["{$row['title']}"] = '<div class="reference-autocomplete">'. $row['rendered'] . '</div>';
    }
  }
  drupal_json($matches);
}

// Update the groups and choices when the name is changed.
//
function merci_staff_update_name() {
  //module_load_include('inc', 'node', 'node.pages');
  $choice_count = count($_POST['choice']);
  $form_state = array('storage' => NULL, 'submitted' => TRUE);
  $form_build_id = $_POST['form_build_id'];

  // Get the form from the cache.
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  // We will run some of the submit handlers so we need to disable redirecting.
  //$form['#redirect'] = FALSE;
  // We need to process the form, prepare for that by setting a few internals
  // variables.
  $form['#post'] = $_POST;
  $form['#programmed'] = FALSE;
  $form_state['post'] = $_POST;

  $dates = $form['#post']['field_merci_date'][0];

  // If a start and end date exist, we have to massage them
  // into the proper format from user input.
  // TODO: is there a more elegant way to do this?
  if ($dates['value']['date'] && $dates['value']['time'] && $dates['value2']['date'] && $dates['value2']['time']) {
    $default_format = $form['#field_info']['field_merci_date']['widget']['input_format'];
    $form_state['values']['field_merci_date'][0] = merci_convert_date_popup($dates, $default_format);
  }
  else {
    $form_state['values']['field_merci_date'][0]['value'] = NULL;
    $form_state['values']['field_merci_date'][0]['value2'] = NULL;
  }

  merci_staff_user_load($form['#post']);

  if (module_exists('og')) {
    unset($form['og_nodeapi']);
    og_form_add_og_audience($form,$form_state);
  }
  // Add the current choices to the form.
  for ($delta = 0; $delta < $choice_count; $delta++) {
    $default = isset($node->choice[$delta]['item']) ? $node->choice[$delta]['item'] : '';

    $form['choice_wrapper']['choice'][$delta] = _merci_choice_form($node, $form_state, $delta, $default);
  }

  merci_staff_user_load();

  form_set_cache($form_build_id, $form, $form_state);
  $form += array(
    '#post' => $_POST,
    '#programmed' => FALSE,
  );
  $form = form_builder($form_id, $form, $form_state);

  unset($form['#prefix'], $form['#suffix']);

  drupal_json(array(
    'status'   => TRUE,
    'data'     => theme('status_messages') . drupal_render($form),
//    'settings' => array('ahah' => $settings['ahah']),
  ));

}


function _merci_staff_potential_references($field, $string = '', $exact_string = FALSE) {
    static $results = array();

    $references = _merci_staff_potential_references_standard($field, $string, $exact_string);

    // Store the results.
    $results[$field['field_name']][$string][$exact_string] = $references;

    return $results[$field['field_name']][$string][$exact_string];
}

/**
 * Helper function for _civicrm_cck_potential_references():
 * referenceable nodes defined by content types.
 */
function _merci_staff_potential_references_standard( $field, $string = '', $exact_string = FALSE, $limit = '10' ) {
    $args = $whereClause = $contactTypes = $contactSubTypes = array();
    
    if ( ! civicrm_initialize( ) ) {
        return;
    }

    require_once 'CRM/Contact/BAO/ContactType.php';
    require_once 'CRM/Core/BAO/UFMatch.php';
    $basicTypes = CRM_Contact_BAO_ContactType::basicTypePairs( );
      
    foreach ( $basicTypes as $name => $label ) {
        if ( is_array( $field[$name] ) ) {
            $contactNames = array_filter( $field[$name] );
            if ( !empty( $contactNames ) ) {
                if ( in_array( $name, $contactNames ) ) {
                    $contactTypes[] = $name;
                } 
                else {
                    $contactSubTypes = array_merge( $contactSubTypes, array_keys( $contactNames ) );
                }
            }
        }
    } 
  
    if ( !empty( $contactTypes ) ) {
        $contactTypes  = implode( "','", $contactTypes );
        $whereClause[] = "contact_type IN ( '{$contactTypes}' )";
    }
    
    if ( !empty( $contactSubTypes ) ) {
        $contactSubTypes = implode( "','", $contactSubTypes );
        $whereClause[]   = "contact_sub_type IN ( '{$contactSubTypes}' )";
    }
   
    $whereClause = empty( $whereClause ) ? '' : '(' . implode( ' OR ', $whereClause ) . ') AND';
    $related_clause = "";

    if (isset($string)) {
        if ($exact_string) {
            $string_clause = " AND display_name = %1";
            $args[] = $string;
        } 
        else {
            $string_clause = " AND display_name LIKE %1";
            $args[] = "%%" . $string ."%";
        }
    }
      
    $q = "
    SELECT civicrm_contact.id, display_name
    FROM civicrm_contact
    JOIN civicrm_uf_match ON civicrm_contact.id = civicrm_uf_match.contact_id
    WHERE $whereClause
    display_name IS NOT NULL
    AND display_name NOT LIKE ''
    AND display_name NOT LIKE '<Last>%%'
    AND display_name NOT LIKE '%@%%'
    AND display_name NOT LIKE '--%%'
    AND display_name NOT LIKE '- -%%'
    AND display_name NOT LIKE ',%%'
    AND display_name NOT LIKE '..%%'
    ". $string_clause ." LIMIT $limit";
    $params = array( 1 => array( $args[0], "String" ) );
    $dao = CRM_Core_DAO::executeQuery( $q, $params );

    $references = array();
    while ($dao->fetch()) {
        $uid = CRM_Core_BAO_UFMatch::getUFId($dao->id);
        $username = db_result(db_query("SELECT name FROM {users} WHERE uid=%d",$uid));
        $references[$dao->id] = array(
                                      'title' => $username,
                                      'rendered' => $dao->display_name,
                                      );
    }

    return $references;
}

