<?php

/*
 * Adds entity object to our list of available arguments for rules_forms.
 */
function merci_rules_events_variable_entity_load($arguments, $variable_name, $variable_info) {
  $entity = $arguments['form_state']['values'];
  $entity_type = array_key_exists('#entity_type', $arguments['form']) ? $arguments['form']['#entity_type'] : NULL;
  if (empty($entity_type)) {
    return NULL;
  } 
  return entity_metadata_wrapper($entity_type, (object) $entity);
}

/**
 * Check if any of the targetted fields conflict.
 */
function merci_rules_condition_conflict($entity, $date_field, $target_field) {

  $entity_type = $entity->type();

  $controller = merci_get_controller($entity_type, $entity, $date_field, $target_field); 
  $ids =  $controller->conflictingTargets();

  if(!empty($ids)) {
    return TRUE;
  }
  return FALSE;
}

/*
 * Load a list of target ids with conflicts.
 */
function merci_rules_action_unavailable_entity_list($entity, $date_field, $target_field) {
  $entity_type = $entity->type();

  $controller = merci_get_controller($entity_type, $entity, $date_field, $target_field); 
  $ids =  $controller->conflictingTargets();
  dpm($ids);
  return array('entity_object_list' => $ids);
}

function merci_rules_conflict_date_value($form, $form_state, $date_element, $item_element, $hours_element) {
  list(,$date_field) = explode(':', $date_element);
  list(,$item_field) = explode(':', $item_element);
  list(,$hours_field) = explode(':', $hours_element);

  $entity = $form_state['values'];

  $entity = (object) $entity;
  $entity_type = & $form['#entity_type'];

  $field_info = field_info_field($item_field);
  $target_type = $field_info['settings']['target_type'];
  $targets = $entity->{$item_field}[LANGUAGE_NONE];

  $context = array(
    'date_field' => $date_field,
    'target_field' => $item_field,
    'langcode'   => LANGUAGE_NONE,
    'status_field' => 'field_status_again',
    'field'   => $field_info,
  );

  $ids = array();
  foreach ($targets as $target) {
    $ids = $target['target_id'];
  }

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $target_type)
    ->entityCondition('entity_id', $ids, 'IN')
    ->fieldCondition($hours_field);
  $result = $query->execute();
  if (isset($result[$target_type])) {
    $items = entity_load($target_type, array_keys($result[$target_type]));
  }
}
