<?php
// $Id$

/**
 * @file
 * merci_daypart_pricing functions
 */

/**
 * Implementation of hook_menu().
 */
function merci_daypart_pricing_menu() {

  $admin = array('administer MERCI');
  
  $items['merci/daypart'] = array(
    'title' => 'Daypart Pricing',
    'description' => 'Takes a node ID or content type and start and end times of the Reservation and returns prince',
    'page arguments' => array(3,4,5),
    'page callback' => 'merci_daypart_pricing',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
   // Standard Administration settings.
  $items['admin/settings/merci/daypart'] = array(
    'title' => 'Daypart Pricing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('merci_daypart_pricing_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => $admin,
    'description' => t('Configure settings for MERCI\'s Daypart Pricing.'),
    'type' => MENU_LOCAL_TASK,
  );


  return $items;
}

/**
 * Builds the admininstration settings form.
 */
function merci_daypart_pricing_admin_settings() {

  $form['merci_use_lowest'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use lowest pricing'),
    '#default_value' => variable_get('merci_default_reservation_status', ''),
    '#description' => t('If the normal hourly pricing is lower than the Daypart pricing, use the hourly pricing.'),
            );
  
  // Hours of operation

  $hours_description = '<div>' . t('Enter military time for both starting and ending time, separated by a dash, in the format') . ' <em>hh:mm-hh:mm</em></div>' . t('ex.') . ' <em>09:00-13:00</em> ' . t('would be start at 9AM, end at `PM. Leave blank to indicate not being used.  A single 24 hour Daypart to enable 24 hour discounts would be ') . '<em>00:00-23:59</em>';
  

  $form['merci_daypart1'] = array(
    '#type' => 'textfield',
    '#title' => t('Daypart 1 hours'),
    '#size' => 11,
    '#maxlength' => 11,
    '#default_value' => variable_get('merci_daypart1', '00:00-11:59'),
    '#description' => $hours_description,
  );
  
  $form['merci_daypart2'] = array(
    '#type' => 'textfield',
    '#title' => t('Daypart 2 hours'),
    '#size' => 11,
    '#maxlength' => 11,
    '#default_value' => variable_get('merci_daypart2', '12:00-23:59'),
    '#description' => $hours_description,
  );
  
  $form['merci_daypart3'] = array(
    '#type' => 'textfield',
    '#title' => t('Daypart 3 hours'),
    '#size' => 11,
    '#maxlength' => 11,
    '#default_value' => variable_get('merci_daypart3', ''),
    '#description' => $hours_description,
  );
  
  return system_settings_form($form);
}

function merci_daypart_pricing($start, $end, $node_type_array) {
  
  
  $items = explode(',', $_POST['items']);
  $dates = array(
    strtotime($_POST['date'][0] . ' ' . $_POST['time'][0]),
    strtotime($_POST['date'][1] . ' ' . $_POST['time'][1]),
  );
  
  watchdog('daypart items', $items[0]);
  watchdog('daypart start', $dates[0]);
  
  $start_date = date_make_date($dates[0]);
  $end_date = date_make_date($dates[1]);

  $hours = round(($dates[1] - $dates[0]) / 3600, 2);
  
  watchdog('daypart hours', $hours);
  
  foreach ($items as $item) {
    watchdog('daypart item', $item);
    
    if (is_numeric($item)) {
      $item_node = node_load($item);
      
      watchdog('daypart resource type', $item_node->type);
      $type = merci_load_content_type_settings($item_node->type);
      watchdog('daypart resource rate', $type->rate_per_hour);
    } else {
      $type = merci_load_content_type_settings($item);
      watchdog('daypart bucket rate', $type->rate_per_hour);
    }

    $fee_hours       = $hours - ($type->fee_free_hours);
    $commercial_cost = $type->rate_per_hour * $hours;
    $member_cost     = ($fee_hours > 0) ? ($type->rate_per_hour * $discount) * $fee_hours : 0;
    $day_rate     = ($type->rate_per_hour * 24);
    
    $commercial_cost_total += $commercial_cost;
    $member_cost_total += $member_cost;
  }

  // create return object
  $return = new StdClass;
  $return->member = $member_cost_total;
  $return->commercial = $commercial_cost_total;
  return drupal_json($return);
}
// merci_daypart_pricing

/**
 * Implements hook_form_alter().
 */
function merci_daypart_pricing_form_alter(&$form, &$form_state, $form_id) {

  if (
    ($form_id == 'merci_reservation_node_form') &&
    ($form['nid']['#value'] == NULL)
  ) {
  
    drupal_add_js(drupal_get_path('module', 'merci_daypart_pricing') . '/js/merci_daypart_pricing.js');

  } // if

} // merci_daypart_pricing_form_alter