<?php

/**
 *  * Implements hook_entity_bundle_field_info_alter().
 */
function merci_max_length_constraint_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node'  && !empty($fields['merci_reservation_items'])) {
    $fields['merci_reservation_items']->addConstraint('MerciMaxLength', array('date_field' => 'merci_reservation_date', 'interval_field' => 'field_max_length_of_reservation'));
  }
}
