<?php


function merci_blackout_dates_merci_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors){
  $field_date_name = $field['settings']['handler_settings']['behaviors']['merci']['merci']['merci_date_field'];

  if (!property_exists($entity, $field_date_name)) {
    return;
  }

  $dates = merci_api_get_local_date_object($field_date_name, $entity->{$field_date_name}[$langcode][0]);
  foreach ($items as $delta => $item) {
    $entity_ids[] = $item['target_id'];
  }
  $entity_items = entity_load($instance['entity_type'], $entity_ids);

  $settings = $field['settings']['handler_settings']['behaviors']['merci']['merci_blackout_dates'];
  $merci_blackout_reference_field_name = $settings['merci_blackout_reference_field'];
  $merci_date_field_name            = $settings['merci_date_field'];


  $start_day = $dates['start']->format('Ymd');
  $end_day = $dates['end']->format('Ymd');

  foreach ($items as $delta => $item) {
    $item_entity = $entity_items[$item['target_id']];
    $instance_info = field_info_instance($instance['entity_type'], $merci_blackout_reference_field_name, $item_entity->type);
    if (empty($instance_info)) {
      continue;
    }

    foreach ($item_entity->{$merci_blackout_reference_field_name}[$langcode] as $hours) {
      $hour_entities = entity_load($instance_info['entity_type'], array($hours['target_id']));
      foreach ($hour_entities as $hour_id => $hour_entity) {
        foreach ($hour_entity->{$merci_date_field_name}[$langcode] as $timefield) {
          $blackout_dates = merci_api_get_local_date_object($merci_date_field_name, $timefield);

          $blackout = $blackout_dates['start']->format('Ymd');

          if ($blackout == $start_day) {
            $errors[$field['field_name']][$langcode][$delta][] = array(
              'error' => 'merci_blackout_dates_start',
              'message' => t('%name: Start time is on a day we are closed.', array('%name' => $instance['label'])),
            );
          }

          if ($blackout == $end_day) {
            $errors[$field['field_name']][$langcode][$delta][] = array(
              'error' => 'merci_blackout_dates_end',
              'message' => t('%name: End time is on a day we are closed.', array('%name' => $instance['label'])),
            );
          }
        }

      }
    }
  }

}
function merci_blackout_dates_merci_settings_form($field, $instance, &$form) {
  /**
   * get all date fields on the site organized by entity and bundle
   */
  $fields_info = field_info_instances();

  /**
   * get all date fields on the site organized by entity and bundle
   */
  $reference_fields = array('disabled' => t('Disabled'));

  $date_fields = array('disabled' => t('Disabled'));
  foreach ($fields_info as $type => $bundles) {
    foreach ($bundles as $name => $bundle) {
      foreach ($bundle as $field_name => $field_info) {
        $more_info = field_info_field($field_name);
        if ( $more_info['type'] == 'datetime' || $more_info['type'] == 'date' || $more_info['type'] == 'datestamp') {
          $date_fields[$field_name] = $field_info['label'];
        }
        if ( $more_info['type'] == 'entityreference') {
          $reference_fields[$field_name] = $field_info['label'];
        }
      }
    }
  }

  $settings = array_key_exists('merci_blackout_dates', $field['settings']['handler_settings']['behaviors']['merci']) ?
    $field['settings']['handler_settings']['behaviors']['merci']['merci_blackout_dates'] : array();
  $default_value = array_key_exists('merci_date_field', $settings) ? $settings['merci_date_field'] : 'disabled';

  $form['merci_blackout_dates'] = array(
    '#type' => 'fieldset',
    '#title' => t('Merci blackout dates'),
    '#collapsible' => TRUE,
    '#collapsed' => $default_value == 'disabled' ? true : false, 
  );
  if (empty($date_fields)) {
    $form['merci_blackout_dates']['merci_time_field'] = array(
      '#markup' => t('Please add a time field to a entity to use to filter reservations.')
    );
  } else {
    $form['merci_blackout_dates']['merci_date_field'] = array(
      '#type' => 'select',
      '#title' => t('Date field'),
      '#options' => $date_fields,
      '#default_value' => $default_value,
      '#description' => t('Select the date field to use to limit reservations of this entity field.'),
    );
  }

  $default_value = array_key_exists('merci_blackout_reference_field', $settings) ? $settings['merci_blackout_reference_field'] : 'disabled';
  if (empty($reference_fields)) {
    $form['merci_blackout_dates']['merci_blackout_reference_field'] = array(
      '#markup' => t('Please add a entityreference field to the user entity to use to filter reservations by permission.')
    );
  } else {


    $form['merci_blackout_dates']['merci_blackout_reference_field'] = array(
      '#type' => 'select',
      '#title' => t('Time reference field'),
      '#options' => $reference_fields,
      '#default_value' => $default_value,
      '#description' => t('Select the entityreference field to use to limit reservations of this entity field.'),
    );
  }
}

