<?php
// $Id$

/**
 * @file
 * merci_template functions
 */

/**
 * Implements hook_form_alter().
 */
function merci_template_form_merci_reservation_node_form_alter(&$form, $form_state) {

  drupal_add_js(drupal_get_path('module', 'merci_template') . '/merci_template.js');

  if (isset($_GET['draft_id']) && is_numeric($_GET['draft_id'])) {
    $draft_id = $_GET['draft_id'];
  }
  $form['update_draft_id'] = array(
    '#type' => 'hidden',
    '#value' => $draft_id,
  );
}
// merci_template_form_alter
/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function merci_template_draft($op, $draft_id, $draft_data = array(), &$form) {
  foreach ($draft_data as $key => $item) {
    if (preg_match("/^choice\((\d{1,5})\)\(item\)$/", $key, $matches)) {
      $delta = $matches[1];
      if ($delta > 2) {
        $form['choice_wrapper']['choice'][$delta] = _merci_choice_form($node, $form_state, $delta);
      }
    }
  }
}
